name: CI_SONATA

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }} Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    defaults:
        run:
            shell: bash -l {0}


    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yaml
          activate-environment: test
          auto-activate-base: false
          
      - name: Download and install anba
        run: |
          git clone https://github.com/ANBA4/anba4.git
          cd anba4
          pip install -e .

      - name: Install SONATA
        run: |
          pip install -e .

      - name: Run example 0
        run: |
          cd examples/0_beams
          python 0_SONATA_init_box_beam_HT_antisym_layup_15_6_SI_SmithChopra91.py
      
      - name: Run example 1
        run: |
          cd examples/1_IEA15MW
          python 1_sonata_IEA15.py
